Functional referral
OSFD-Winter/OSFD-Frontend pull request #40
Opened 2022-11-20 20:08 UTC by BrandonC123

Task: 
first lets change "Enter Wallet REFFERAL LINK" with "REFERRER" & hide send button then

1-) user should be able to generate / copy referral link of themselves  (by using copy button in second textfield)

2-) the ones clicked the referral link will have their referrer text field filled  (the first text field)

3-) make the reward dynamic usd equivalent of 0.5 eth

2022-11-20 20:09 UTC, BrandonC123 commented
Hiding the button was causing some issues with styling so refactored it a bit to be more dynamic.
![image](https://user-images.githubusercontent.com/23132411/202923798-3848fdad-e789-445e-8eb8-48033471796d.png)

2022-11-24 12:19 UTC, tanerdurmaz requested changes
also lets change default values in input text boxes. 

referrer will have "enter wallet address ex. 0x4ba..."
referral link will have "connect your wallet" if wallet is not connected

2022-11-24 12:19 UTC, tanerdurmaz commented on package.json
> +    "@firebase/storage": "^0.9.14",
we dont need this

2022-11-24 12:19 UTC, tanerdurmaz commented on pages/index.tsx
> +  ]);
this update shouldnt change index.tsx, if its only indentation issue latest precommit script should fix it you can pull it from main branch

2022-11-24 12:19 UTC, tanerdurmaz commented on styles/globals.css
> +.referral-row {
lets dont add these in global.css 
we have tailwind now

2022-11-25 05:00 UTC, BrandonC123 commented
Seems I messed up a couple lines of code while merging index.tsx initially, should be good now. Here's the updated referral with and without wallet connected:
![conne](https://user-images.githubusercontent.com/23132411/203904337-a590606f-bee9-4952-9ba2-13398bf65c0c.png)
![w ref](https://user-images.githubusercontent.com/23132411/203904373-e3208493-9378-4e43-936b-1790aed527f2.png)

2022-11-25 09:58 UTC, tanerdurmaz approved these changes

2022-11-25 09:58 UTC, merged