Mint preview TypeScript refactor
OSFD-Winter/OSFD-Frontend pull request #56
Opened 2022-11-27 22:21 UTC by BrandonC123

Task: 
- remove // @ts-nocheck
- and fix ts errors in mintPreview.tsx

2022-11-28 09:17 UTC, tanerdurmaz commented on components/mintPreview.tsx
> +      <Image src={image} width="0" height="0" sizes="20vw" className="w-full h-auto" alt="" />
we want to keep image ratio

2022-11-28 09:19 UTC, tanerdurmaz requested changes
need to keep aspect ratio of iamges

2022-11-28 23:29 UTC, BrandonC123 commented
Reverted Image to img tag and also added back in missing tailwind code for referral component

2022-11-29 11:26 UTC, tanerdurmaz approved these changes

2022-11-29 11:27 UTC, tanerdurmaz commented
when chance can you share this in general channel one sentence is enough like
"Mint preview typescript refactor" and add link to the this pr
now on devs will share each update

2022-11-29 11:27 UTC, merged